#!/usr/bin/env python3
"""Generate a flash-resident HID usage lookup from USB-IF's attached JSON.

The JSON file is the attachment shipped inside the HID Usage Tables PDF.  The
generator deliberately emits no dynamic containers: ESP32 firmware searches
sorted constexpr arrays in place.
"""

import argparse
import json
from pathlib import Path


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="HidUsageTables.json")
    parser.add_argument("--output", default="components/ble_client_hid/usage_data.cpp")
    args = parser.parse_args()

    source = Path(args.input)
    destination = Path(args.output)
    data = json.loads(source.read_text(encoding="utf-8"))
    pages = sorted(data["UsagePages"], key=lambda page: int(page["Id"]))

    usage_rows: list[tuple[int, str, str]] = []
    page_rows: list[tuple[int, str, int, int]] = []
    for page in pages:
        start = len(usage_rows)
        usages = sorted(page["UsageIds"], key=lambda usage: int(usage["Id"]))
        for usage in usages:
            usage_rows.append(
                (int(usage["Id"]), usage["Name"], "|".join(usage.get("Kinds", [])))
            )
        page_rows.append((int(page["Id"]), page["Name"], start, len(usages)))

    version = (
        f'{data["UsageTableVersion"]}.{data["UsageTableRevision"]}'
        f'.{data["UsageTableSubRevisionInternal"]}'
    )
    lines = [
        "// Generated by generate_cpp_usage_tables.py; do not edit.",
        f"// USB-IF HID Usage Tables version {version}.",
        '#include "usages.h"',
        "",
        "namespace esphome {",
        "namespace ble_client_hid {",
        "namespace {",
        "struct UsageRecord { uint16_t id; const char *name; const char *kinds; };",
        "struct PageRecord { uint16_t id; const char *name; uint16_t first; uint16_t count; };",
        "constexpr UsageRecord USAGES[] = {",
    ]
    lines.extend(
        f"  {{{usage_id}, {cpp_string(name)}, {cpp_string(kinds)}}},"
        for usage_id, name, kinds in usage_rows
    )
    lines.extend(["};", "constexpr PageRecord PAGES[] = {"])
    lines.extend(
        f"  {{{page_id}, {cpp_string(name)}, {first}, {count}}},"
        for page_id, name, first, count in page_rows
    )
    lines.extend(
        [
            "};",
            "template<typename T, typename F>",
            "const T *binary_find(const T *begin, const T *end, uint16_t id, F get_id) {",
            "  while (begin < end) {",
            "    const T *middle = begin + (end - begin) / 2;",
            "    const uint16_t current = get_id(*middle);",
            "    if (current < id) begin = middle + 1;",
            "    else if (current > id) end = middle;",
            "    else return middle;",
            "  }",
            "  return nullptr;",
            "}",
            "const PageRecord *find_page(uint16_t page) {",
            "  return binary_find(PAGES, PAGES + sizeof(PAGES) / sizeof(PAGES[0]), page,",
            "                     [](const PageRecord &entry) { return entry.id; });",
            "}",
            "}  // namespace",
            f'const char *const HID_USAGE_TABLE_VERSION = "{version}";',
            "const char *lookup_usage_page_name(uint16_t page) {",
            "  const PageRecord *entry = find_page(page);",
            "  return entry == nullptr ? nullptr : entry->name;",
            "}",
            "const char *lookup_usage_name(uint16_t page, uint16_t usage) {",
            "  const PageRecord *page_entry = find_page(page);",
            "  if (page_entry == nullptr || page_entry->count == 0) return nullptr;",
            "  const UsageRecord *begin = USAGES + page_entry->first;",
            "  const UsageRecord *entry = binary_find(begin, begin + page_entry->count, usage,",
            "                                               [](const UsageRecord &value) { return value.id; });",
            "  return entry == nullptr ? nullptr : entry->name;",
            "}",
            "const char *lookup_usage_kinds(uint16_t page, uint16_t usage) {",
            "  const PageRecord *page_entry = find_page(page);",
            "  if (page_entry == nullptr || page_entry->count == 0) return nullptr;",
            "  const UsageRecord *begin = USAGES + page_entry->first;",
            "  const UsageRecord *entry = binary_find(begin, begin + page_entry->count, usage,",
            "                                               [](const UsageRecord &value) { return value.id; });",
            "  return entry == nullptr || entry->kinds[0] == '\\0' ? nullptr : entry->kinds;",
            "}",
            "}  // namespace ble_client_hid",
            "}  // namespace esphome",
            "",
        ]
    )
    destination.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
